# Generated by Django 4.2.1 on 2023-06-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_rename_meseros_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='procedencia',
            field=models.CharField(default=12, max_length=12),
            preserve_default=False,
        ),
    ]
