# Generated by Django 4.2.1 on 2023-06-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meseros',
            name='procedencia',
            field=models.CharField(default='peru', max_length=12),
        ),
    ]
