# Generated by Django 4.2.1 on 2023-06-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0002_meseros_procedencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meseros',
            name='procedencia',
            field=models.CharField(default='', max_length=12),
        ),
    ]
